-- begin LIBRARYTEST_BOOK
alter table LIBRARYTEST_BOOK add constraint FK_LIBRARYTEST_BOOK_AUTHOR foreign key (AUTHOR_ID) references LIBRARYTEST_AUTHOR(ID)^
create index IDX_LIBRARYTEST_BOOK_AUTHOR on LIBRARYTEST_BOOK (AUTHOR_ID)^
-- end LIBRARYTEST_BOOK
-- begin LIBRARYTEST_GENRE_BOOK_LINK
alter table LIBRARYTEST_GENRE_BOOK_LINK add constraint FK_LGBL_GENRE foreign key (GENRE_ID) references LIBRARYTEST_GENRE(ID)^
alter table LIBRARYTEST_GENRE_BOOK_LINK add constraint FK_LGBL_BOOK foreign key (BOOK_ID) references LIBRARYTEST_BOOK(ID)^
-- end LIBRARYTEST_GENRE_BOOK_LINK
