alter table LIBRARYTEST_BOOK add constraint FK_LIBRARYTEST_BOOK_AUTHOR foreign key (AUTHOR_ID) references LIBRARYTEST_AUTHOR(ID);
create index IDX_LIBRARYTEST_BOOK_AUTHOR on LIBRARYTEST_BOOK (AUTHOR_ID);
